//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkolaProjektniCentar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkolaContext : DbContext
    {
        public SkolaContext()
            : base("name=SkolaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KontaktTelefon> KontaktTelefon { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<MailListe> MailListe { get; set; }
        public virtual DbSet<Osoba> Osoba { get; set; }
        public virtual DbSet<Skola> Skola { get; set; }
        public virtual DbSet<TipMaila> TipMaila { get; set; }
        public virtual DbSet<TipTelefona> TipTelefona { get; set; }
    }
}
